

steps:
  - name: gcr.io/${_PROJECT_ID}/packer
    env:
      - PROJECT_ID=${_PROJECT_ID}
    args:
      - build
      - -force
      - -var
      - PROJECT_ID=${_PROJECT_ID}
      - 'packer/build-win-image.json'
      - -var
      - SUBNETWORK='default'
      - 'packer/build-win-image.json'
timeout: 720s

substitutions:
  _PROJECT_ID: flow-testing-project

